name: Tests

on:
  push:
    - branches: 'main'
  pull_request:
    - branches: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: pdo, pdo_sqlite
          php-version: 8.2

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install and build frontend assets
        run: |
          yarn ci
          yarn run dev

      - name: Run tests
        run: php artisan test

